version: "3"
services:
  web:
    image: web:1.0
    build:
      context: ./docker/django/.
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: :24224
        tag: django_app
    env_file:
      - web.env
    depends_on:
      - fluent-bit

  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    build:
      context: ./docker/fluentbit/.
    ports:
      - 24224:24224
      - 24224:24224/udp